name: Daily Commit to Maintain Streak

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at 12 AM UTC (5 AM Pakistan)
  workflow_dispatch:

permissions:
  contents: write      # REQUIRED so Action can push commits

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Daily Commit
        run: |
          echo "Streak Log: $(date)" >> streak-log.txt
          git config --global user.email "aqsaabbasi2690@gmail.com"
          git config --global user.name "Aqsa Abbasi"
          git add streak-log.txt
          git commit -m "ðŸ”¥ Keeping streak alive â€” $(date)"
          git push
